#pragma once
#include <string>
#include <filesystem>
#include <optional>
#include <array>
#include <functional>
#include "Utilities/Result.h"
#include "Utilities/Color.h"
#include "Utilities/RestrictTypes.h"
#include <glad/glad.h>
#include "Utilities/Vector.h"
#include "Typedefs.h"
#include "Message/Messages.h"
#include "Constants.h"
#include "Utilities/Matrix33.h"
